// Shared Text Sizes
const TEXT_SMALL = 14;
const TEXT_MEDIUM = 28;
const TEXT_LARGE = 48;

export const CONFIG = {
    // World
    GRID_SIZE: 32,
    WORLD_WIDTH: 55,
    WORLD_HEIGHT: 40,
    // Sprigs
    MAX_SPRIGS: 500,
    START_SPRIGS: 5,
    MAX_SPEED: 100.0,
    SPRIG_RADIUS: 15.0,
    SPRIG_VIEW_RADIUS: 200.0,
    NEST_VIEW_RADIUS: 350.0,
    // Lifecycle
    HUNGER_INTERVAL: 60.0,
    HUNGER_PENALTY: 0.75,
    HUNGER_BUFFER: 1,
    HUNGER_RISK: 0.5,
    SPAWN_COST: 20,
    SPAWN_TIME: 10.0,
    REGEN_INTERVAL: 15.0,
    REGEN_AMOUNT: 5,
    // Wander
    WANDER_SPEED: 50.0,
    WANDER_DIST: 60.0,
    WANDER_TMIN: 2.0,
    WANDER_TMAX: 5.0,
    // Steering
    STEER_SEPARATION_WEIGHT: 1.0,
    STEER_COHESION_WEIGHT: 0.5,
    STEER_ALIGNMENT_WEIGHT: 0.0,    // standard boids force, unused
    STEER_SEEK_WEIGHT: 1.0,
    STEER_AVOID_WEIGHT: 2.5,
    STEER_PATH_WEIGHT: 0.75,
    FRICTION_BASE: 0.0,
    FRICTION_MUD: 0.5,
    FRICTION_WATER: 0.8,
    // Devtools
    SPAWN_PER_TAP: 1,
    SPAWN_PER_SEC: 10,
    TAP_THRESHOLD_MS: 200,
    TERRAIN_RADIUS: 50.0,
    ERASER_RADIUS: 40.0,
    DEBUG_SPRIG_VECTORS: false,
    DEBUG_STRUCTURE_LABELS: false,
    // Player GUI
    COMMAND_RADIUS: 50.0,
    WAYPOINT_TOLERANCE: 40.0,
    HARVEST_SIGNAL_RADIUS: 300.0,
    HARVEST_SIGNAL_DURATION: 30.0,
    PATROL_RADIUS: 100.0,
    SIGNAL_ALPHA: 0.25,
    // Progression
    XP_BASE: 100,
    LEVEL_CAP: 10,
    XP_PER_HAUL: 1,
    XP_PER_HIT: 1,
    XP_PER_KILL: 30,
    // Hauling
    BASE_CARRY_CAPACITY: 5,
    HP_PER_HAUL_LEVEL: 30,
    CARRY_PER_HAUL_LEVEL: 1,
    // Combat
    BASE_HP: 100,
    BASE_ATTACK: 10,
    BASE_DEFENSE: 5,
    SPRIG_ATTACK_RANGE: 50.0,
    SPRIG_ATTACK_COOLDOWN: 1.0,
    RETREAT_HP_THRESHOLD: 0.25,
    RETREAT_STEERING_WEIGHT: 5.0,
    HP_PER_FIGHT_LEVEL: 50,
    ATTACK_PER_FIGHT_LEVEL: 3,
    DEFENSE_PER_FIGHT_LEVEL: 1,
    // Threats
    MAX_BURROWS: 10,
    BURROW_LIMIT: 50,
    THIEF_HP: 20,
    THIEF_ATTACK: 0,
    THIEF_DEFENSE: 0,
    THIEF_SPEED_MULT: 1.2,
    THIEF_LEASH_RADIUS: 500.0,
    THIEF_CORNERED_RADIUS: 100.0,
    THIEF_CORNERED_ATK: 20,
    THIEF_CORNERED_DEF: 5,
    THIEF_STEP_INTERVAL: 80,
    // Visuals
    TEXT_SIZE_SMALL: TEXT_SMALL,
    TEXT_SIZE_MEDIUM: TEXT_MEDIUM,
    TEXT_SIZE_LARGE: TEXT_LARGE,

    PARTICLE_SIZE_DAMAGE: TEXT_MEDIUM,
    PARTICLE_SIZE_LEVEL: TEXT_LARGE,
    PARTICLE_SIZE_XP: TEXT_SMALL,
    PARTICLE_SIZE_EMOTE: TEXT_SMALL,
    
    PARTICLE_FOOTPRINT_LIFE: 10.0,
    
    EMOTE_EAT: "🍕",
    EMOTE_HAUL: "📦",
    EMOTE_COMBAT: "⚔️",
    EMOTE_THIEF_HURT: "🫨",
    EMOTE_THIEF_STEAL: "😈",
    // Colors
    COLOR_TEXT_DAMAGE: 0xFF0000,
    COLOR_TEXT_XP_HAUL: 0xFFFFFF,
    COLOR_TEXT_XP_FIGHT: 0xFF8888,
    COLOR_TEXT_LEVEL_HAUL: 0xFFD700,
    COLOR_TEXT_LEVEL_FIGHT: 0xFF4500,
    COLOR_PARTICLE_GOLD: 0xFFD700,
    COLOR_PARTICLE_SPARK: 0xFFFF00,
};

export const SCREEN_WIDTH = CONFIG.GRID_SIZE * CONFIG.WORLD_WIDTH;
export const SCREEN_HEIGHT = CONFIG.GRID_SIZE * CONFIG.WORLD_HEIGHT;