export const CONFIG = {
    TILE_SIZE: 24,
    WORLD_WIDTH: 40, // tiles
    WORLD_HEIGHT: 30, // tiles
    MAX_SPRIGS: 2000,
    MAX_SPEED: 50.0, // Pixels per second
    SPRIG_RADIUS: 5.0,
    SCENT_STRENGTH: 1000.0,
};

export const SCREEN_WIDTH = CONFIG.TILE_SIZE * CONFIG.WORLD_WIDTH;
export const SCREEN_HEIGHT = CONFIG.TILE_SIZE * CONFIG.WORLD_HEIGHT;
