export const TOOL_NAMES = {
    HAND: 'HAND',
    PAINT: 'PAINT',
    BUILD: 'BUILD',
    SPAWN: 'SPAWN',
    ERASER: 'ERASER',
    HARVEST: 'HARVEST',
    COMMAND: 'COMMAND',
    PATROL: 'PATROL'
};

export const TOOL_ORDER = [
    TOOL_NAMES.HAND,
    TOOL_NAMES.COMMAND,
    TOOL_NAMES.SPAWN,
    TOOL_NAMES.HARVEST,
    TOOL_NAMES.PATROL,
    TOOL_NAMES.PAINT,
    TOOL_NAMES.BUILD,
    TOOL_NAMES.ERASER
];
